(cl:defpackage aprilslam-srv
  (:use )
  (:export
   "MOVESTATE"
   "<MOVESTATE-REQUEST>"
   "MOVESTATE-REQUEST"
   "<MOVESTATE-RESPONSE>"
   "MOVESTATE-RESPONSE"
   "RESETPARAMS"
   "<RESETPARAMS-REQUEST>"
   "RESETPARAMS-REQUEST"
   "<RESETPARAMS-RESPONSE>"
   "RESETPARAMS-RESPONSE"
  ))

