// Generated by gencpp from file aprilslam/Apriltags.msg
// DO NOT EDIT!


#ifndef APRILSLAM_MESSAGE_APRILTAGS_H
#define APRILSLAM_MESSAGE_APRILTAGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <aprilslam/Apriltag.h>

namespace aprilslam
{
template <class ContainerAllocator>
struct Apriltags_
{
  typedef Apriltags_<ContainerAllocator> Type;

  Apriltags_()
    : header()
    , sensor_id(0)
    , apriltags()  {
    }
  Apriltags_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensor_id(0)
    , apriltags(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _sensor_id_type;
  _sensor_id_type sensor_id;

   typedef std::vector< ::aprilslam::Apriltag_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::aprilslam::Apriltag_<ContainerAllocator> >::other >  _apriltags_type;
  _apriltags_type apriltags;





  typedef boost::shared_ptr< ::aprilslam::Apriltags_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aprilslam::Apriltags_<ContainerAllocator> const> ConstPtr;

}; // struct Apriltags_

typedef ::aprilslam::Apriltags_<std::allocator<void> > Apriltags;

typedef boost::shared_ptr< ::aprilslam::Apriltags > ApriltagsPtr;
typedef boost::shared_ptr< ::aprilslam::Apriltags const> ApriltagsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aprilslam::Apriltags_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aprilslam::Apriltags_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aprilslam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'aprilslam': ['/home/cyy/ws/jz_project/catkin_ws/src/caliber/aprilslam/aprilslam/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aprilslam::Apriltags_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aprilslam::Apriltags_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aprilslam::Apriltags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aprilslam::Apriltags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aprilslam::Apriltags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aprilslam::Apriltags_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aprilslam::Apriltags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00d264e04e8ef34a601ad83c77c08f44";
  }

  static const char* value(const ::aprilslam::Apriltags_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00d264e04e8ef34aULL;
  static const uint64_t static_value2 = 0x601ad83c77c08f44ULL;
};

template<class ContainerAllocator>
struct DataType< ::aprilslam::Apriltags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aprilslam/Apriltags";
  }

  static const char* value(const ::aprilslam::Apriltags_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aprilslam::Apriltags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ApriltagsStamped\n\
std_msgs/Header header\n\
int32 sensor_id\n\
Apriltag[] apriltags\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: aprilslam/Apriltag\n\
# Apriltag\n\
int32 id\n\
string family\n\
float64 size\n\
int32 hamming_distance\n\
geometry_msgs/Point center\n\
geometry_msgs/Point[] corners\n\
geometry_msgs/Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::aprilslam::Apriltags_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aprilslam::Apriltags_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensor_id);
      stream.next(m.apriltags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Apriltags_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aprilslam::Apriltags_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aprilslam::Apriltags_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensor_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sensor_id);
    s << indent << "apriltags[]" << std::endl;
    for (size_t i = 0; i < v.apriltags.size(); ++i)
    {
      s << indent << "  apriltags[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aprilslam::Apriltag_<ContainerAllocator> >::stream(s, indent + "    ", v.apriltags[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // APRILSLAM_MESSAGE_APRILTAGS_H
