// Generated by gencpp from file aprilslam/Apriltag.msg
// DO NOT EDIT!


#ifndef APRILSLAM_MESSAGE_APRILTAG_H
#define APRILSLAM_MESSAGE_APRILTAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Pose.h>

namespace aprilslam
{
template <class ContainerAllocator>
struct Apriltag_
{
  typedef Apriltag_<ContainerAllocator> Type;

  Apriltag_()
    : id(0)
    , family()
    , size(0.0)
    , hamming_distance(0)
    , center()
    , corners()
    , pose()  {
    }
  Apriltag_(const ContainerAllocator& _alloc)
    : id(0)
    , family(_alloc)
    , size(0.0)
    , hamming_distance(0)
    , center(_alloc)
    , corners(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _family_type;
  _family_type family;

   typedef double _size_type;
  _size_type size;

   typedef int32_t _hamming_distance_type;
  _hamming_distance_type hamming_distance;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _corners_type;
  _corners_type corners;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::aprilslam::Apriltag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aprilslam::Apriltag_<ContainerAllocator> const> ConstPtr;

}; // struct Apriltag_

typedef ::aprilslam::Apriltag_<std::allocator<void> > Apriltag;

typedef boost::shared_ptr< ::aprilslam::Apriltag > ApriltagPtr;
typedef boost::shared_ptr< ::aprilslam::Apriltag const> ApriltagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aprilslam::Apriltag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aprilslam::Apriltag_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aprilslam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'aprilslam': ['/home/cyy/ws/jz_project/catkin_ws/src/caliber/aprilslam/aprilslam/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aprilslam::Apriltag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aprilslam::Apriltag_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aprilslam::Apriltag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aprilslam::Apriltag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aprilslam::Apriltag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aprilslam::Apriltag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aprilslam::Apriltag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae7cf1294fdf73ec26bf785570c3a80d";
  }

  static const char* value(const ::aprilslam::Apriltag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae7cf1294fdf73ecULL;
  static const uint64_t static_value2 = 0x26bf785570c3a80dULL;
};

template<class ContainerAllocator>
struct DataType< ::aprilslam::Apriltag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aprilslam/Apriltag";
  }

  static const char* value(const ::aprilslam::Apriltag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aprilslam::Apriltag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Apriltag\n\
int32 id\n\
string family\n\
float64 size\n\
int32 hamming_distance\n\
geometry_msgs/Point center\n\
geometry_msgs/Point[] corners\n\
geometry_msgs/Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::aprilslam::Apriltag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aprilslam::Apriltag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.family);
      stream.next(m.size);
      stream.next(m.hamming_distance);
      stream.next(m.center);
      stream.next(m.corners);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Apriltag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aprilslam::Apriltag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aprilslam::Apriltag_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "family: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.family);
    s << indent << "size: ";
    Printer<double>::stream(s, indent + "  ", v.size);
    s << indent << "hamming_distance: ";
    Printer<int32_t>::stream(s, indent + "  ", v.hamming_distance);
    s << indent << "center: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "corners[]" << std::endl;
    for (size_t i = 0; i < v.corners.size(); ++i)
    {
      s << indent << "  corners[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.corners[i]);
    }
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APRILSLAM_MESSAGE_APRILTAG_H
