// Generated by gencpp from file aprilslam/MoveState.msg
// DO NOT EDIT!


#ifndef APRILSLAM_MESSAGE_MOVESTATE_H
#define APRILSLAM_MESSAGE_MOVESTATE_H

#include <ros/service_traits.h>


#include <aprilslam/MoveStateRequest.h>
#include <aprilslam/MoveStateResponse.h>


namespace aprilslam
{

struct MoveState
{

typedef MoveStateRequest Request;
typedef MoveStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveState
} // namespace aprilslam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aprilslam::MoveState > {
  static const char* value()
  {
    return "943495411fa218d7df068416952dd94f";
  }

  static const char* value(const ::aprilslam::MoveState&) { return value(); }
};

template<>
struct DataType< ::aprilslam::MoveState > {
  static const char* value()
  {
    return "aprilslam/MoveState";
  }

  static const char* value(const ::aprilslam::MoveState&) { return value(); }
};


// service_traits::MD5Sum< ::aprilslam::MoveStateRequest> should match 
// service_traits::MD5Sum< ::aprilslam::MoveState > 
template<>
struct MD5Sum< ::aprilslam::MoveStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aprilslam::MoveState >::value();
  }
  static const char* value(const ::aprilslam::MoveStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aprilslam::MoveStateRequest> should match 
// service_traits::DataType< ::aprilslam::MoveState > 
template<>
struct DataType< ::aprilslam::MoveStateRequest>
{
  static const char* value()
  {
    return DataType< ::aprilslam::MoveState >::value();
  }
  static const char* value(const ::aprilslam::MoveStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aprilslam::MoveStateResponse> should match 
// service_traits::MD5Sum< ::aprilslam::MoveState > 
template<>
struct MD5Sum< ::aprilslam::MoveStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aprilslam::MoveState >::value();
  }
  static const char* value(const ::aprilslam::MoveStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aprilslam::MoveStateResponse> should match 
// service_traits::DataType< ::aprilslam::MoveState > 
template<>
struct DataType< ::aprilslam::MoveStateResponse>
{
  static const char* value()
  {
    return DataType< ::aprilslam::MoveState >::value();
  }
  static const char* value(const ::aprilslam::MoveStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APRILSLAM_MESSAGE_MOVESTATE_H
