// Generated by gencpp from file aprilslam/MoveStateResponse.msg
// DO NOT EDIT!


#ifndef APRILSLAM_MESSAGE_MOVESTATERESPONSE_H
#define APRILSLAM_MESSAGE_MOVESTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aprilslam
{
template <class ContainerAllocator>
struct MoveStateResponse_
{
  typedef MoveStateResponse_<ContainerAllocator> Type;

  MoveStateResponse_()
    : error_message()  {
    }
  MoveStateResponse_(const ContainerAllocator& _alloc)
    : error_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_message_type;
  _error_message_type error_message;





  typedef boost::shared_ptr< ::aprilslam::MoveStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aprilslam::MoveStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveStateResponse_

typedef ::aprilslam::MoveStateResponse_<std::allocator<void> > MoveStateResponse;

typedef boost::shared_ptr< ::aprilslam::MoveStateResponse > MoveStateResponsePtr;
typedef boost::shared_ptr< ::aprilslam::MoveStateResponse const> MoveStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aprilslam::MoveStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aprilslam::MoveStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aprilslam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'aprilslam': ['/home/cyy/ws/jz_project/catkin_ws/src/caliber/aprilslam/aprilslam/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aprilslam::MoveStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aprilslam::MoveStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aprilslam::MoveStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aprilslam::MoveStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aprilslam::MoveStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aprilslam::MoveStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aprilslam::MoveStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a13979422fc129b30b15994450a302b5";
  }

  static const char* value(const ::aprilslam::MoveStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa13979422fc129b3ULL;
  static const uint64_t static_value2 = 0x0b15994450a302b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::aprilslam::MoveStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aprilslam/MoveStateResponse";
  }

  static const char* value(const ::aprilslam::MoveStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aprilslam::MoveStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string error_message\n\
\n\
";
  }

  static const char* value(const ::aprilslam::MoveStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aprilslam::MoveStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aprilslam::MoveStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aprilslam::MoveStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APRILSLAM_MESSAGE_MOVESTATERESPONSE_H
